In [2]:
import numpy as np
import matplotlib.pyplot as plt
import os, sys
import pandas as pd

root = '/usr/local/serenceslab/maggie/shapeDim/'

sys.path.append(os.path.join(root, 'Analysis'))
from code_utils import file_utils

In [43]:
sublist = np.arange(1,8)
idx = -1
sdat = pd.DataFrame(columns = ['subject','run','num_events','hit_rate','num_FA'])

for ss in sublist:

    rc = 0
    for se in [1,2,3,4]:

        bdir = os.path.join(root, 'DataBehavior', 'S%02d'%ss, 'Session%d'%se)
        if not os.path.exists(bdir):
            continue
        silh_files = os.listdir(bdir)
        silh_files = [ff for ff in silh_files if 'Silh' in ff]

        if len(silh_files)>0:
            assert(len(silh_files)==1)
            TheData = file_utils.load_mat_behav_data(os.path.join(bdir, silh_files[0]))
            print('found %d runs for S%02d'%(len(TheData), ss))
            for rr in range(len(TheData)):
                rc+=1; idx+=1
                dat = TheData[rr]['data']

                sdat = sdat.append(pd.DataFrame({'subject': ss, \
                                         'run': rc, \
                                         'num_events': dat['EvtCount'], \
                                         'hit_rate': dat['hit_rate'], \
                                         'num_FA': dat['FACount']}, index=[idx]))

found 2 runs for S01
found 3 runs for S01
found 2 runs for S02
found 2 runs for S02
found 2 runs for S02
found 2 runs for S03
found 2 runs for S03
found 2 runs for S03
found 1 runs for S04
found 1 runs for S04
found 3 runs for S04
found 1 runs for S05
found 6 runs for S05
found 2 runs for S06
found 1 runs for S06
found 3 runs for S06
found 1 runs for S07
found 1 runs for S07
found 2 runs for S07

In [44]:
sdat

   subject run num_events  hit_rate num_FA
0        1   1         13  0.384615      8
1        1   2         22  1.000000      0
2        1   3         21  0.857143      2
3        1   4         13  0.923077      0
4        1   5         15  0.866667      0
5        2   1         20  0.500000      2
6        2   2         19  0.736842      1
7        2   3         22  0.181818      5
8        2   4         15  0.866667      1
9        2   5         16  0.875000      0
10       2   6         17  0.823529      0
11       3   1         14  0.785714      1
12       3   2         20  0.800000      0
13       3   3         22  0.727273      0
14       3   4         16  0.750000      1
15       3   5         10  0.900000      0
16       3   6         18  0.833333      0
17       4   1         20  0.150000      7
18       4   2         16  0.687500      0
19       4   3         17  0.588235      3
20       4   4         14  0.571429      2
21       4   5         21  0.571429      2
22       5   1         24  0.625000      3
23       5   2         10  0.700000      1
24       5   3         21  0.904762      0
25       5   4         17  0.941176      0
26       5   5         21  0.714286      0
27       5   6         15  0.800000      0
28       5   7         18  0.777778      0
29       6   1         13  0.615385      0
30       6   2         19  0.789474      1
31       6   3         25  0.720000      0
32       6   4         15  0.800000      0
33       6   5         17  0.941176      0
34       6   6         14  0.928571      0
35       7   1         15  0.066667     24
36       7   2         14  0.714286      1
37       7   3         18  0.888889      1
38       7   4         20  1.000000      0

#### Print some simple statistics

In [50]:
subj_avg_hitrates = [np.mean(sdat['hit_rate'][sdat['subject']==ss]) for ss in sublist]
m = np.mean(subj_avg_hitrates)
s = np.std(subj_avg_hitrates)
print('average hit rate (mean +/- std):')
print('%.2f +/- %.2f'%(m, s))

average hit rate (mean +/- std):
0.72 +/- 0.10

In [54]:
subj_avg_fa = [np.mean(sdat['num_FA'][sdat['subject']==ss]) for ss in sublist]
m = np.mean(subj_avg_fa)
s = np.std(subj_avg_fa)
print('average num false alarms (mean +/- std):')
print('%.2f +/- %.2f'%(m, s))

average num false alarms (mean +/- std):
1.98 +/- 2.05

In [53]:
evtcount = sdat['num_events']
m = np.mean(evtcount)
mi = np.min(evtcount)
ma = np.max(evtcount)
print('average event count (mean, [min, max]):')
print('%d, [%d, %d]'%(m, mi, ma))

average event count (mean, [min, max]):
17, [10, 25]